<?=$this->doctype()?>
<html>
    <head>
        <?
            //ViewHelper que carga los metas con la información necesaria
            echo $this->headTitle();
            echo $this->headersdescriptivos();
            $this->headLink()->appendStylesheet("/css/estilos.css");
            $this->headScript()->appendFile("/js/jquery/jquery.js");
            $this->headScript()->appendFile("/js/scripts.js");
            $this->headScript()->appendFile("/js/funciones.js");
            $this->headScript()->appendFile("/js/bootstrap.min.js");
            $this->headScript()->appendFile("/js/jquery/blockUIModal.js");

            echo $this->headScript();
            echo $this->headLink();
            echo $this->jQuery();
        ?>
    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top" data-dropdown="dropdown">
            <div class="navbar-inner">
                <div class="container">
                    <a class="brand" href="/buscador/buscador/"><img height="20px" src="http://s17.postimage.org/6lltgrdnf/trobador_P.png"/></a>
                    <div class="pull-left"><?=$this->menu()?></div>

                    <?=$this->menuadmin()?>
                        <div class="pull-right">
                    <?php
                    if (!Zend_Auth::getInstance()->hasIdentity()) {
                        echo $this->login(new Usuarios_Form_Login());
                    } else { ?>
                            <?php echo $this->loggedin(); ?>
                    <?php } ?>
                        </div>
                </div>
            </div>
        </div><!-- fin topbar -->

        <div class="container">

            <!-- Se imprimen los mensajes de error/aviso al usuario -->
            <center>
             <? $messenger = Zend_Controller_Action_HelperBroker::getStaticHelper('FlashMessenger');
                $messages = array_merge($messenger->getCurrentMessages(),$messenger->getMessages());
                foreach ($messages as $message) { ?>
                    <div id="alerta" class="alert-message info fade in">
                        <a id="closealerta" class="close" data-dismiss="alert-message" href="#">&times;</a>
                        <?=$this->escape($this->translate($message))?>
                    </div>
                <?
                }
                $messenger->clearMessages();
                ?>
            </center>
            <div id="content">
                <?=$this->layout()->content?>
            </div>

            <footer>
                <div id="language-selector">
                    <?=new Buscador_Form_Elegiridioma()?>
                </div>
                <?=$this->footer()?>
            </footer>

            <div class="modal hide" id="myModal">
                <div id="modal-header" class="modal-header">
                    <a id ="btnCerrarModal" class="close closeTab">&times;</a>
                </div>
                <div class="modal-body">
                    <p><?=Zend_Registry::get('Zend_Translate')->translate('m114')?></p>
                </div>
                <div id="modal-footer" class="modal-footer">
                    <a href="#" id ="btnCerrarModal1" class="btn"><?=Zend_Registry::get('Zend_Translate')->translate('m111')?></a>
                </div>
            </div>

        </div>
    </body>
</html>
