<div class="header">
    <center>
        <h1><img src="http://s18.postimage.org/bav9fb92h/trobador.png"/></h1>
    </center>
</div>
<div class="hero-unit">
    <h2><?=Zend_Registry::get('Zend_Translate')->translate('m026')?></h2>
    <center>
    <?
        echo $this->form;
    ?>
    </center>
</div>

<?    if($this->num > 0) { ?>
            <h2><?=Zend_Registry::get('Zend_Translate')->translate('m027')?> "<?php echo $this->searchTopic; ?>"</h2>
            <div class="right">
                <b><?=Zend_Registry::get('Zend_Translate')->translate('m028')?>:</b> <?=$this->num?>
            </div>
            <hr>


            <div id="search-results">
            <?php
            $proyectos = $this->proyectos;
            $versiones = $this->versiones;

            foreach ($this->resultado as $resul) {
                ?>

                <table class="table-bordered">
                    <tbody>
                        <tr>
                            <th><?=Zend_Registry::get('Zend_Translate')->translate('m029')?></th>
                            <td><?=$proyectos[$resul['version_id']]?></td>
                        </tr>
                        <tr>
                            <th><?=Zend_Registry::get('Zend_Translate')->translate('m030')?></th>
                            <td><?=$versiones[$resul['version_id']]?></td>
                        </tr>
                        <tr>
                            <th>Original string</th>
                            <td><?php echo str_replace($this->searchTopic, '<span class="highlight">'.$this->searchTopic.'</span>', $resul['original_unit'])?></td>
                        </tr>
                        <tr>
                            <th><?=Zend_Registry::get('Zend_Translate')->translate('m031')?></th>
                            <td><?=$resul['translated_unit']?></td>
                        </tr>
                    </tbody>
                </table>
            <?
            }
            $params = array('cadena' => $this->cadena, 'idiomaOrigen' => $this->idiomaOrigen, 'idiomaDestino' => $this->idiomaDestino);
            ?>
            </div>
            <?php echo $this->paginationControl($this->paginator, 'Sliding', 'controlpaginacion.phtml', $params); ?>
 <?   } else if ($this->mensaje){ ?>
            <div class="hero-unit">
            <h2><?=Zend_Registry::get('Zend_Translate')->translate('m027')?></h2>
                <?=$this->mensaje?>
            </div>
<?     } ?>
