<?php $params = array('cadena' => $this->cadena, 'idiomaOrigen' => $this->idiomaOrigen, 'idiomaDestino' => $this->idiomaDestino); ?>
<div class="main-page">
    <?php if($this->num < 1) { ?>
    <div class="page-header">
        <a href="/"><h1 class="ir">Trobador</h1></a>
        <h2><?=Zend_Registry::get('Zend_Translate')->translate('m026')?></h2>
    </div>
    <?php } ?>
    <div class="search-form">
        <?php echo $this->form; ?>
    </div>

    <? if ($this->num > 0) { ?>
        <div class="left">
            <h3><?=Zend_Registry::get('Zend_Translate')->translate('m027')?> "<?php echo $this->searchTopic; ?>" : Showing form <?php echo abs($this->page-1) * 30 ?> to <?php echo $this->page * 30 ?> of <?=$this->paginator->getTotalItemCount()?> results</h3>
        </div>

        <div id="search-results">

        <?php
        $proyectos = $this->proyectos;
        $versiones = $this->versiones;

        foreach ($this->resultado as $resul) {
            ?>

            <table class="table-bordered">
                <tbody>
                    <tr>
                        <th><?=Zend_Registry::get('Zend_Translate')->translate('m029')?></th>
                        <td><?=$versiones[$resul['version_id']]['project_name']?></td>
                    </tr>
                    <tr>
                        <th><?=Zend_Registry::get('Zend_Translate')->translate('m030')?></th>
                        <td><?=$versiones[$resul['version_id']]['version_name']?></td>
                    </tr>
                    <tr>
                        <th>Original string</th>
                        <td><?php echo preg_replace('/('.$this->searchTopic.')/i', '<span class="highlight">$1</span>', $resul['original_unit'])?></td>
                    </tr>
                    <tr>
                        <th><?=Zend_Registry::get('Zend_Translate')->translate('m031')?></th>
                        <td><?=$resul['translated_unit']?></td>
                    </tr>
                </tbody>
            </table>
        <?php } ?>
        </div>
        <?php echo $this->paginationControl($this->paginator, 'Sliding', 'controlpaginacion.phtml', $params); ?>
     <?   } else if ($this->mensaje){ ?>
            <h2><?=Zend_Registry::get('Zend_Translate')->translate('m027')?></h2>
            <?=$this->mensaje?>
    <? } ?>
</div>
