<div class="header">
    <center>
        <h1>TROBADOR<!--<img src="../../imagenes/gol.png" />--></h1>
    </center>
</div>
<div class="hero-unit">
    <h2><?=Zend_Registry::get('Zend_Translate')->translate('m026')?></h2>
    <center>
    <?
        echo $this->form;
    ?>
    </center>
</div>

<?    if($this->num > 0) { ?>
        <div class="hero-unit">
            <h2><?=Zend_Registry::get('Zend_Translate')->translate('m027')?></h2>

            <div class="alinearTextoIzq">
                <b><?=Zend_Registry::get('Zend_Translate')->translate('m028')?>:</b> <?=$this->num?>
            </div>
            <?
            $i = 0;
            $proyectos = $this->proyectos;
            $versiones = $this->versiones;
            foreach ($this->resultado as $resul) {
                ?>
                <div class="fondo alinearTextoIzq">
                    <b><?=Zend_Registry::get('Zend_Translate')->translate('m029')?>: </b><?=$proyectos[$i]?><br>
                    <b><?=Zend_Registry::get('Zend_Translate')->translate('m030')?>: </b><?=$versiones[$i]?><br>
                    <b><?=Zend_Registry::get('Zend_Translate')->translate('m031')?>: </b><br>
                    <div class="justificarTexto">
                        <?=$resul['translated_unit']?>
                    </div>
                </div><br><br>
            <?
                $i++;
            }
            $params = array('cadena' => $this->cadena, 'idiomaOrigen' => $this->idiomaOrigen, 'idiomaDestino' => $this->idiomaDestino);
            ?>
            <?php echo $this->paginationControl($this->paginator, 'Sliding', 'controlpaginacion.phtml', $params); ?>
        </div>
 <?   } else if ($this->mensaje){ ?>
            <div class="hero-unit">
            <h2><?=Zend_Registry::get('Zend_Translate')->translate('m027')?></h2>
                <?=$this->mensaje?>
            </div>
<?     } ?>
