<div class="hero-unit">
    <h2><?=Zend_Registry::get('Zend_Translate')->translate('m008')?></h2>
    <a id="linkNuevoUsuario" href="#"><?=Zend_Registry::get('Zend_Translate')->translate('m107')?></a>
    <center>
<?  if($this->usuarioRegistrado) {
        echo $this->usuarioRegistrado;
    }
?>
<?   if(!$this->mensaje) { ?>
        <table class="tabla">
            <thead>
                <tr>
                    <th><?=Zend_Registry::get('Zend_Translate')->translate('m049')?></th>
                    <th><?=Zend_Registry::get('Zend_Translate')->translate('m064')?></th>
                    <th><?=Zend_Registry::get('Zend_Translate')->translate('m108')?></th>
                    <th><?=Zend_Registry::get('Zend_Translate')->translate('m109')?></th>
                    <th><?=Zend_Registry::get('Zend_Translate')->translate('m110')?></th>
                    <th><?=Zend_Registry::get('Zend_Translate')->translate('m056')?></th>
                    <th><?=Zend_Registry::get('Zend_Translate')->translate('m000')?></th>
                </tr>
            </thead>
            <tbody>
                <tr id="frmNuevoUsuario">
                    <?=$this->formNuevoUsuario->render()?>
                    <td id="linkCancelar">
                        <a href="#"><?=Zend_Registry::get('Zend_Translate')->translate('m111')?></a>
                    </td><td></td>
                </tr>
                <?
                    foreach ($this->usuarios as $usuario){
                ?>
                    <tr>
                        <?= new Administracion_Form_Editarusuario($usuario)?>
                        <?  $acl = new Usuarios_Model_Acl();
                            $tablaRoles = new Administracion_Model_DbTable_Roles();
                        if(!$acl->esAdmin($tablaRoles->getRoleNamePorId($usuario['role_id']))){ ?>
                            <?= new Administracion_Form_Eliminarusuario($usuario)?>
                        <?} else {
                            ?><td></td><?
                        } ?>
                        <td><a href="/administracion/usuarios/asignarproxectosusuario?idUsuario=<?=$usuario['user_id']?>"><?=Zend_Registry::get('Zend_Translate')->translate('m112')?></a></td>
                        <!-- <td><a href="/administracion/usuarios/eliminarusuario?idUsuario=<? //echo $usuario['user_id'];?>">Eliminar</a></td> -->
                    </tr>

               <? } ?>
            </tbody>
        </table>
<?   } else {
            echo $this->mensaje;
        }
?>
    </center>
</div>
