<div class="hero-unit">
    <h2><?=Zend_Registry::get('Zend_Translate')->translate('m086')?></h2>
    <center>
        <?
        //if($this->monte) {echo $this->monte;}
            /*echo $this->form->render();
            if($this->mensajeFrm){
                echo $this->mensajeFrm;
            }*/
        ?>
<?      if(!$this->mensaje) { ?>
        <table class="tabla">
            <thead>
                <tr>
                    <th><?=Zend_Registry::get('Zend_Translate')->translate('m098')?></th>
                    <?foreach($this->roles as $rol){ ?>
                        <th><?=$rol['role_name']?></th>
                    <?}?>
                </tr>
            </thead>
            <tbody>
                <?
                    foreach ($this->recursos as $recurso){
                ?>
                    <tr>
                        <td><b><?=$recurso['resource_name']?></b><br><br>
                            <?
                                foreach($this->privilegios as $privilegio){
                                    echo $privilegio['privilege_name'];?><br><br>
                            <?  }?>
                        </td>

                        <?foreach($this->roles as $rol){ ?>
                            
                            <td><br><br>
                                 <?
                                foreach($this->privilegios as $privilegio){
                                    //echo $recurso['resource_name']." ".$rol['role_name']." ".$privilegio['privilege_name'];
                                    $options = array(
                                        'role_id' => $rol['role_id'],
                                        'resource_id' => $recurso['resource_id'],
                                        'privilege_id' => $privilegio['privilege_id'],
                                    );
                                    echo new Administracion_Form_Asignarrecursos($options);

                                    ?>
                               <? }?>
                            </td>
                        <?}?>
                        
                    </tr>

               <? } ?>
            </tbody>
        </table>
<?      } else {
            echo $this->mensaje;
        }
?>
    </center>
</div>