<div class="hero-unit">
    <h2><?=Zend_Registry::get('Zend_Translate')->translate('m009')?></h2>
    <center>
        <ul>
            <li><a href="/administracion/recursos/verroles"><?=Zend_Registry::get('Zend_Translate')->translate('m099')?></a></li>
            <li><a href="/administracion/recursos/verrecursos"><?=Zend_Registry::get('Zend_Translate')->translate('m100')?></a></li>
            <li><a href="/administracion/recursos/verprivilegios"><?=Zend_Registry::get('Zend_Translate')->translate('m101')?></a></li>
            <li><a href="/administracion/recursos/asignar"><?=Zend_Registry::get('Zend_Translate')->translate('m092')?></a></li>
        </ul>
    </center>
</div>