<div class="hero-unit">
    <h2><?=Zend_Registry::get('Zend_Translate')->translate('m009')?></h2>
    <center>
        <div style="max-height: 600px; max-width:250px;background-color: green;">
        <ul style="list-style: none;">
            <li style="float: left;padding: 5px 10px 5px 10px;"><a href="/administracion/recursos/verroles"><img width="80px" src="http://s13.postimage.org/72y1iuo7n/roles.png" /><span style="display: block;"><?=Zend_Registry::get('Zend_Translate')->translate('m099')?></span></a></li>
            <li style="float: left;padding: 5px 10px 5px 10px;"><a href="/administracion/recursos/verrecursos"><img width="80px" src="http://s10.postimage.org/omj4u1kp1/resources.png" /><span style="display: block;"><?=Zend_Registry::get('Zend_Translate')->translate('m100')?></span></a></li>
            <li style="float: left;clear:both;padding: 5px 10px 5px 10px;"><a href="/administracion/recursos/verprivilegios"><img width="80px" src="http://s17.postimage.org/fm88pfurv/privileges.png" /><span style="display: block;"><?=Zend_Registry::get('Zend_Translate')->translate('m101')?></span></a></li>
            <li style="float: left;padding: 5px 10px 5px 10px;"><a href="/administracion/recursos/asignar"><img width="80px" src="http://s15.postimage.org/kyocvbfnb/settings.png" /><span style="display: block;"><?=Zend_Registry::get('Zend_Translate')->translate('m092')?></span></a></li>
        </ul>
            </div>
    </center>
    <div style="clear:both;"> </div>
</div>