<div class="hero-unit">
    <h2><?=Zend_Registry::get('Zend_Translate')->translate('m103')?></h2>
    <center>
        <?
            echo $this->form->render();
            if($this->mensajeFrm){
                echo $this->mensajeFrm;
            }
        ?>
        <h2><?=Zend_Registry::get('Zend_Translate')->translate('m076')?></h2>
        <table class="tabla">
            <thead>
                <tr>
                    <th><?=Zend_Registry::get('Zend_Translate')->translate('m049')?></th>
                    <th><?=Zend_Registry::get('Zend_Translate')->translate('m094')?></th>
                    <?
                        $acl = new Usuarios_Model_Acl();
                        $auth = Zend_Auth::getInstance();
                        $data = $auth->getStorage()->read();

                        if ($acl->esAdmin($data['role_name'])) {?>
                            <th><?=Zend_Registry::get('Zend_Translate')->translate('m056')?></th>
                    <?}?>
                </tr>
            </thead>
            <tbody>
                <?
                    foreach ($this->recursos as $recurso){
                ?>
                    <tr>
                        <td><?=$recurso['resource_name']?></td>
                        <td><?=$recurso['resource_description']?></td>
                        <?if ($acl->esAdmin($data['role_name'])) {?>
                            <td><a href="/administracion/recursos/eliminarrecurso?idRecurso=<?=$recurso['resource_id']?>"><?=Zend_Registry::get('Zend_Translate')->translate('m056')?></a></td>
                        <?}?>
                    </tr>

               <? } ?>
            </tbody>
        </table>
    </center>
</div>