<div class="hero-unit">
    <h2><?=Zend_Registry::get('Zend_Translate')->translate('m104')?></h2>
    <center>
        <?=$this->form->render()?>
        <h2><?=Zend_Registry::get('Zend_Translate')->translate('m074')?></h2>
        <table class="tabla">
            <thead>
                <tr>
                    <th><?=Zend_Registry::get('Zend_Translate')->translate('m049')?></th>
                    <th><?=Zend_Registry::get('Zend_Translate')->translate('m094')?></th>
                    <?
                        $acl = new Usuarios_Model_Acl();
                        $auth = Zend_Auth::getInstance();
                        $data = $auth->getStorage()->read();

                        if ($acl->esAdmin($data['role_name'])) {?>
                            <th><?=Zend_Registry::get('Zend_Translate')->translate('m056')?></th>
                    <?}?>
                </tr>
            </thead>
            <tbody>
                <?
                    foreach ($this->roles as $rol){
                ?>
                    <tr>
                        <td><?=$rol['role_name']?></td>
                        <td><?=$rol['role_description']?></td>
                        <?if ($acl->esAdmin($data['role_name']) && ($rol['role_name'] != 'invitado') && ($rol['role_name'] != 'basico') && ($rol['role_name'] != 'administrador')) {?>
                            <td><a href="/administracion/recursos/eliminarrol?idRol=<?=$rol['role_id']?>"><?=Zend_Registry::get('Zend_Translate')->translate('m056')?></a></td>
                        <?} else {?>
                            <td><?=Zend_Registry::get('Zend_Translate')->translate('err036')?></td>
                        <?}?>
                    </tr>

               <? } ?>
            </tbody>
        </table>
    </center>
</div>