<div class="hero-unit">
    <h2><?=Zend_Registry::get('Zend_Translate')->translate('m003')?></h2>
    <center>
<?      if(!$this->mensaje) { ?>
        <table class="tabla">
            <thead>
                <tr>
                    <th><?=Zend_Registry::get('Zend_Translate')->translate('m049')?></th>
                    <th><?=Zend_Registry::get('Zend_Translate')->translate('m057')?></th>
                    <th><?=Zend_Registry::get('Zend_Translate')->translate('m058')?></th>
                    <th><?=Zend_Registry::get('Zend_Translate')->translate('m055')?></th>
                    <?
                        $acl = new Usuarios_Model_Acl();
                        $auth = Zend_Auth::getInstance();
                        $data = $auth->getStorage()->read();

                        if ($acl->esAdmin($data['role_name'])) {?>
                            <th><?=Zend_Registry::get('Zend_Translate')->translate('m056')?></th>
                    <?  } ?>
                </tr>
            </thead>
            <tbody>
                <?  $tablaUsuarios = new Usuarios_Model_DbTable_Users();
                    foreach ($this->proyectos as $proyecto){
                ?>
                    <tr>
                        <td><a href="/proyectos/proyectos/verproyecto?idProyecto=<?=$proyecto['project_id']?>"><?=$proyecto['project_name']?></a></td>
                        <td><?=$tablaUsuarios->getNamePorId($proyecto['user_id'])?></td>
                        <td><?=$proyecto['percent_completed']."%"?></td>
                        <td><?=$proyecto['creation_date']?></td>
                        <?if ($acl->esAdmin($data['role_name'])) { ?>
                            <td><a href="/proyectos/proyectos/eliminarproyecto?idProyecto=<?=$proyecto['project_id']?>"><?=Zend_Registry::get('Zend_Translate')->translate('m056')?></a></td>
                        <?}?>
                    </tr>

               <? } ?>
            </tbody>
        </table>
<?      } else {
            echo $this->mensaje;
        }
?>
    </center>
</div>
