<?php if ($this->pageCount):?>
<div class="paginationControl">
<!-- Previous page link -->
<?php if (isset($this->previous)): ?>
  <a href="<?= $this->url(array('page' => $this->previous, 'cadena'=> $this->cadena, 'idiomaOrigen' => $this->idiomaOrigen, 'idiomaDestino' => $this->idiomaDestino)); ?>">&lt; <?=Zend_Registry::get('Zend_Translate')->translate('m024')?></a> |
<?php else: ?>
  <span class="disabled">&lt; <?=Zend_Registry::get('Zend_Translate')->translate('m024')?></span> |
<?php endif; ?>

<!-- Numbered page links -->
<?php foreach ($this->pagesInRange as $page): ?>
  <?php if ($page != $this->current): ?>
    <a href="<?= $this->url(array('page' => $page,'cadena'=> $this->cadena, 'idiomaOrigen' => $this->idiomaOrigen, 'idiomaDestino' => $this->idiomaDestino)); ?>"><?= $page; ?></a> |
  <?php else: ?>
    <?= $page; ?> |
  <?php endif; ?>
<?php endforeach; ?>

<!-- Next page link -->
<?php if (isset($this->next)): ?>
  <a href="<?= $this->url(array('page' => $this->next,'cadena'=> $this->cadena, 'idiomaOrigen' => $this->idiomaOrigen, 'idiomaDestino' => $this->idiomaDestino)); ?>"><?=Zend_Registry::get('Zend_Translate')->translate('m025')?> &gt;</a>
<?php else: ?>
  <span class="disabled"><?=Zend_Registry::get('Zend_Translate')->translate('m025')?> &gt;</span>
<?php endif; ?>
</div>
<?php endif; ?>