<div class="page-header">
    <h2><?=Zend_Registry::get('Zend_Translate')->translate('m042')?></h2>
</div>
<?php  if (!$this->mensaje) { ?>
<table id="tablaProyectosTotales" class="table table-bordered">
    <thead>
        <tr>
            <th class="left"><?=Zend_Registry::get('Zend_Translate')->translate('m049')?></th>
            <th style="width:140px;"><?=Zend_Registry::get('Zend_Translate')->translate('m057')?></th>
            <th style="width:140px;"><?=Zend_Registry::get('Zend_Translate')->translate('m055')?></th>
        </tr>
    </thead>
    <tbody>
        <?  $tablaUsuarios = new Usuarios_Model_DbTable_Users();
            foreach ($this->proyectos as $proyecto){
        ?>
            <tr>
                <td class="left"><a href="/proyectos/proyectos/verproyecto?idProyecto=<?=$proyecto['project_id']?>"><?=$proyecto['project_name']?></a></td>
                <td><?=$tablaUsuarios->getNamePorId($proyecto['user_id'])?></td>
                <td><?=$proyecto['creation_date']?></td>
            </tr>

       <? } ?>
    </tbody>
</table>
<?php
} else {
    echo $this->mensaje;
}
