<div class="page-header">
        <h2><?=Zend_Registry::get('Zend_Translate')->translate('m009')?></h2>
</div>
<div class="clearfix">
    <ul style="list-style: none; width:30%; margin:0 auto;">
        <li style="float: left;padding: 5px 10px 5px 10px;"><a href="/administracion/recursos/verroles"><img width="80px" src="/imagenes/roles.png" /><span style="display: block;"><?=Zend_Registry::get('Zend_Translate')->translate('m099')?></span></a></li>
        <li style="float: left;padding: 5px 10px 5px 10px;"><a href="/administracion/recursos/verrecursos"><img width="80px" src="/imagenes/resources.png" /><span style="display: block;"><?=Zend_Registry::get('Zend_Translate')->translate('m100')?></span></a></li>
        <li style="float: left;clear:both;padding: 5px 10px 5px 10px;"><a href="/administracion/recursos/verprivilegios"><img width="80px" src="/imagenes/privileges.png" /><span style="display: block;"><?=Zend_Registry::get('Zend_Translate')->translate('m101')?></span></a></li>
        <li style="float: left;padding: 5px 10px 5px 10px;"><a href="/administracion/recursos/asignar"><img width="80px" src="/imagenes/settings.png" /><span style="display: block;"><?=Zend_Registry::get('Zend_Translate')->translate('m092')?></span></a></li>
    </ul>
</div>