<div class="page-header">
    <h2 style="clear:both;"><?=Zend_Registry::get('Zend_Translate')->translate('m103')?></h2>
</div>
<div style="float:right;">
    <a id="linkVolver" href="/administracion/recursos/index">
        <img height="35px" src="http://s7.postimage.org/got4jyvnb/volver.png"
        alt="<?=Zend_Registry::get('Zend_Translate')->translate('m118')?>"
        title="<?=Zend_Registry::get('Zend_Translate')->translate('m118')?>"/>
    </a>
</div>

<?php
    echo $this->form->render();
    if ($this->mensajeFrm) {
        echo $this->mensajeFrm;
    }
?>
<h2><?=Zend_Registry::get('Zend_Translate')->translate('m076')?></h2>
<table class="tabla">
    <thead>
        <tr>
            <th><?=Zend_Registry::get('Zend_Translate')->translate('m049')?></th>
            <th><?=Zend_Registry::get('Zend_Translate')->translate('m094')?></th>
            <?
                $acl = new Usuarios_Model_Acl();
                $auth = Zend_Auth::getInstance();
                $data = $auth->getStorage()->read();

                if ($acl->esAdmin($data['role_name'])) {?>
                    <th style="width:100px;"><?=Zend_Registry::get('Zend_Translate')->translate('m056')?></th>
            <?}?>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->recursos as $recurso) { ?>
        <tr>
            <td><?=$recurso['resource_name']?></td>
            <td><?=$recurso['resource_description']?></td>
            <?if ($acl->esAdmin($data['role_name'])) {?>
                <td><a class="btn" href="/administracion/recursos/eliminarrecurso?idRecurso=<?=$recurso['resource_id']?>"><i class="icon-trash"></i> <?=Zend_Registry::get('Zend_Translate')->translate('m056')?></a></td>
            <?}?>
        </tr>
       <?php } ?>
    </tbody>
</table>
