<div class="hero-unit">
    <h2><?=Zend_Registry::get('Zend_Translate')->translate('m011')?></h2>
    <center>
        <h4 class="moverIzq"><?=Zend_Registry::get('Zend_Translate')->translate('m069')?></h4>
        <?=$this->form->render()?>

        <div class="separador"></div>
        
        <h4 class="moverIzq"><?=Zend_Registry::get('Zend_Translate')->translate('m070')?></h4>
        <?=$this->formCambiarPass->render()?>
    
    </center>
</div>