<div class="hero-unit">
    <div style="float:right;">
        <a id="linkVolver" href="/administracion/usuarios/gestionusuarios">
            <img height="35px" src="http://s7.postimage.org/got4jyvnb/volver.png" 
            alt="<?=Zend_Registry::get('Zend_Translate')->translate('m118')?>"
            title="<?=Zend_Registry::get('Zend_Translate')->translate('m118')?>"/>
        </a>
    </div>
    
    <h2 style="clear:both;"><?=Zend_Registry::get('Zend_Translate')->translate('m089')?></h2>
    
    <center>

        <table class="tabla">
            <thead>
                <tr>
                    <th><?=Zend_Registry::get('Zend_Translate')->translate('m105')?></th>
                    <th><?=Zend_Registry::get('Zend_Translate')->translate('m092')?></th>
                </tr>
            </thead>
            <tbody>
                <?=$this->formAsignarProyectos?>
            </tbody>
        </table>
        <?
            if($this->mensaje != "") {
                echo $this->mensaje;
            }
        ?>
<?      if($this->proyectos[0] != null) { ?>
            <h2><?=Zend_Registry::get('Zend_Translate')->translate('m106')?></h2>
            <table class="tabla">
                <thead>
                    <tr>
                        <th><?=Zend_Registry::get('Zend_Translate')->translate('m049')?></th>
                        <th><?=Zend_Registry::get('Zend_Translate')->translate('m056')?></th>
                    </tr>
                </thead>
                <tbody>
            <?  foreach ($this->proyectos as $proyecto){ ?>
                    <tr>
                        <td><?=$proyecto['project_name']?></td>
                        <td><a href="/administracion/usuarios/eliminarproxectoasignadousuario?idProyecto=<?=$proyecto['project_id']?>&idUsuario=<?=$this->idUsuario?>"><?=Zend_Registry::get('Zend_Translate')->translate('m056')?></a></td>
                    </tr>
            <?  } ?>
                </tbody>
            </table>
<?      } else {
            ?><?=Zend_Registry::get('Zend_Translate')->translate('err037')?><?
        }
?>
    </center>
</div>
