<h2><?=Zend_Registry::get('Zend_Translate')->translate('m008')?></h2>
    <a  style="float:right;" id="linkNuevoUsuario" href="#"><img height="35px" src="http://s16.postimage.org/6x0gxqg8x/nuevo_Usuario.png"
                                           alt="<?=Zend_Registry::get('Zend_Translate')->translate('m107')?>"
                                           title="<?=Zend_Registry::get('Zend_Translate')->translate('m107')?>"/>
    </a>
<hr>
<?  if($this->usuarioRegistrado) {
        echo $this->usuarioRegistrado;
    }
?>
<?   if(!$this->mensaje) { ?>
        <table id="tablaUsuarios" class="tabla">
            <thead>
                <tr>
                    <th><?=Zend_Registry::get('Zend_Translate')->translate('m049')?></th>
                    <th><?=Zend_Registry::get('Zend_Translate')->translate('m064')?></th>
                    <th><?=Zend_Registry::get('Zend_Translate')->translate('m108')?></th>
                    <th><?=Zend_Registry::get('Zend_Translate')->translate('m109')?></th>
                    <th><?=Zend_Registry::get('Zend_Translate')->translate('m110')?></th>
                    <th><?=Zend_Registry::get('Zend_Translate')->translate('m056')?></th>
                    <th><?=Zend_Registry::get('Zend_Translate')->translate('m000')?></th>
                </tr>
            </thead>
            <tbody>
                <tr id="frmNuevoUsuario">
                    <?=$this->formNuevoUsuario->render()?>
                    <td id="linkCancelar">
                        <a href="#"><?=Zend_Registry::get('Zend_Translate')->translate('m111')?></a>
                    </td><td></td>
                </tr>
                <?  $i = 0;
                    foreach ($this->usuarios as $usuario){
                ?>
                    <tr>
                        <?= new Administracion_Form_Editarusuario($usuario)?>
                        <?  $acl = new Usuarios_Model_Acl();
                            $tablaRoles = new Administracion_Model_DbTable_Roles();
                        if(!$acl->esAdmin($tablaRoles->getRoleNamePorId($usuario['role_id']))){ ?>
                            <?//= new Administracion_Form_Eliminarusuario($usuario)?>
                            <td><a id="btnModal<?=$i?>" onclick='addEliminarUsuario(<?=$usuario['user_id']?>,"<?=Zend_Registry::get('Zend_Translate')->translate('m117')?>","<?=Zend_Registry::get('Zend_Translate')->translate('m115')?>")' href="#"><?=Zend_Registry::get('Zend_Translate')->translate('m056')?></a></td>
                        <?} else {
                            ?><td></td><?
                        } ?>
                        <td><a  href="/administracion/usuarios/asignarproxectosusuario?idUsuario=<?=$usuario['user_id']?>"><?=Zend_Registry::get('Zend_Translate')->translate('m112')?></a></td>
                    </tr>

               <? $i = $i + 1;} ?>
            </tbody>
        </table>
<?   } else {
            echo $this->mensaje;
        }
?>
